title: The title
author: Erik H
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is a project for a class I am taking, hope you like it!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
